---
title: "Clonal Analysis Utilities in APackOfTheClones"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Clonal Analysis Utilities in APackOfTheClones}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
data: 'Compiled: `r format(Sys.Date(), "%B %d, %Y")`'
---

## Introduction

There is a small collection of potentially useful functions to modify clonal expansion plots and work with clonal data that may be relevant.

## Modifying the Clone Size Legend

The `removeLegend` and `overlayLegend` functions both takes in an existing APackOfTheClones plot to either remove or change its position/aesthetics on the plot by directly modifying the ggplot object.

## Getting Clone Sizes as a List

`scRepertoire` counts and store the clone sizes in a column of the seurat object metadata. The `countCloneSizes` function returns this information in a list where each element is a table object corresponding to the clonotype frequencies for that cluster, and a cluster with no clonotypes will have an empty table at its index. It also allows for the same filtering arguments as seen in `RunAPOTC` and `vizAPOTC`.

## TODO

- getSharedClones
- getReductionCentroids

## Highlighting Specific Clonotypes

The `scRepertoire` package has a function `scRepertoire::highlightClones` that highlights specific points in the dimensional reduction plot that correspond to user clonotype inputs and darkening everything else. `showCloneHighlight` is the APackOfTheClones equivalent that does so for each clonotype circle:

```R
showCloneHighlight(
    apotc_ggplot,
    sequence,
    color_each = TRUE,
    default_color = "#808080",
    fill_legend = TRUE
)
```

The function takes in a plot `apotc_ggplot` generated by `APOTCPlot`/`vizAPOTC` and modifies its underlying ggplot data to highlight/dim clones in `sequence`. Read the function level docs for more information on how to customize the coloring of highlights with `color_each` and `default_color`.

A potentially useful application is to inspect the shared clonotypes:

```{r}
# load data
pbmc <- get(data("combined_pbmc))

# create the APackOfTheClones plot
apotc_plot <- vizAPOTC(pbmc, clonecall = "aa", verbose = FALSE)

# get the shared clonotypes
shared_clonotypes <- names(getSharedClones(pbmc, clonecall = "aa"))

# highlight the first 3 shared clones
apotc_plot %>%
    showCloneHighlight(shared_clonotypes[1:3])
```
