# Produce modified ggplot object of an APackOfTheClones plot with an extra slot
# hack fix - the clone size slot stores the autogenerated legend sizes
ApotcGGPlot <- function(ggplot_obj, apotc_obj) {
    apotc_obj@clusters <- list()
    apotc_obj@clone_sizes <- list(estimate_legend_sizes(apotc_obj))
    ggplot_obj$APackOfTheClones <- apotc_obj
    ggplot_obj
}

is_an_apotc_ggplot <- function(ggplot_obj, detail = NA) {
    is_apotc <- inherits(ggplot_obj, "ggplot") && !is.null(ggplot_obj$APackOfTheClones)
    if (is.na(detail)) {
        return(is_apotc)
    } else {
        undetailed <- is_undetailed(ggplot_obj)
        return(is_apotc && undetailed == detail)
    }
}
on_failure(is_an_apotc_ggplot) <- function(call, env) {
    detail <- call$detail
    ggplot_obj <- call$x
    is_apotc <- inherits(ggplot_obj, "ggplot") && !is.null(ggplot_obj$APackOfTheClones)
    if (is.na(detail)) {
        if (!is_apotc) {
            paste0(deparse(call$x), " is not an APackOfTheClones ggplot")
        } else {
            paste0(deparse(call$x), " is an APackOfTheClones ggplot, but failed for unknown reason.")
        }
    } else {
        undetailed <- is_undetailed(ggplot_obj)
        if (!is_apotc) {
            paste0(deparse(call$x), " is not an APackOfTheClones ggplot")
        } else if (undetailed != detail) {
            paste0(deparse(call$x), " is an APackOfTheClones ggplot, but detail does not match: expected detail=", detail, ", got detail=", undetailed)
        } else {
            paste0(deparse(call$x), " is an APackOfTheClones ggplot, but failed for unknown reason.")
        }
    }
}

# getter
get_apotcdata <- function(apotc_ggplot_obj) {
    apotc_ggplot_obj$APackOfTheClones
}

# based on the hack fix - get the estimated legend sizes in a apot ggplot
get_estimated_legend_sizes <- function(apotc_ggplot_obj) {
    get_raw_clone_sizes(get_apotcdata(apotc_ggplot_obj))[[1]]
}
