# load packages
library(Seurat)
library(ggplot2)
library(ggforce)
library(dplyr)
library(hash)
library(data.table)
library(R6)
library(utils)

#' Visualize T cell clonal expansion with a ball-packing plot.
#'
#' Integrates a cell ranger T cell library into a Seurat object with a UMAP
#' reduction. Then gets sizes of unique clones and utilizes a circle-packing
#' algorithm to pack circles representing individual clones in approximately
#' the same UMAP coordinates and clusters into a ggplot object.
#'
#' @param seurat_obj Seurat object with a UMAP reduction.
#' @param tcr_df Dataframe of the T cell library generated by Cell Ranger
#' @param clone_scale_factor numeric. Decides how much to scale each circle. Usually should be kept at around 0.01 to somewhat maintain UMAP structure
#' @param rad_scale_factor numeric. indicates how much the radii of the clones should decrease to add a slight gap between all of them. Defaults to 1 but 0.85-0.95 values are recommended.
#' @param res The number of points on the generated path per full circle.
#' @param ORDER logical. Decides if the largest clones should be at the cluster centroids
#' @param try_place If `TRUE`, always minimizes distance from a newly placed circle to the origin
#' @param progbar logical. Decides if visual cues print to the REPL of the packing progress
#' @param repulse CURRENTLY BUGGED! DO NOT SET TO `TRUE`. The intented functionality is: If `TRUE`, will attempt to push overlapping clusters away from each other.
#' @param repulsion_threshold numeric. The radius that cluster overlap is acceptable
#' @param repulsion_strength numeric. The smaller the value the less the clusters repulse each other
#' @param max_repulsion_iter numeric. The number of repulsion iterations.
#' @param use_default_theme If `TRUE`, the resulting plot will have the same theme as the seurat UMAP
#' @param show_origin logical. If `TRUE`, only the centers of each circle will be plotted
#' @param retain_axis_scales If `TRUE`, approximately maintains the axis scales of the original UMAP
#' @param modify_obj If `TRUE`, will modify the current seurat object after integration. Else has no effect on the input seurat object
#'
#' @return Returns a ggplot2 object of the ball packing plot. Can be operated on like normal ggplot objects
#'
#' @concept circle_packing
#'
#' @seealso \code{\link{integrate_tcr}}
#'
#' @export
#'
#' @examples
#' \dontrun{
#' library(Seurat)
#' library(readr)
#' library(scballpack)
#'
#' # run sc-RNAseq pipeline to produce a seurat_object
#'
#' seurat_object <- RunUMAP(seurat_object)
#' TCR_dataframe <- read.csv("file_location/all_contig_annotations.csv")
#'
#' # produce and show the ball-packing plot
#' ball_pack_plot <- clonal_expansion_plot(seurat_object, TCR_dataframe)
#' ball_pack_plot
#' }
#'
clonal_expansion_plot <- function(
    seurat_obj, tcr_df,
    res = 360,
    clone_scale_factor = 0.01,
    rad_scale_factor = 1,
    ORDER = TRUE,
    try_place = TRUE,
    progbar = TRUE,
    repulse = FALSE, # need to fix...
    repulsion_threshold = 1,
    repulsion_strength = 0.05,
    max_repulsion_iter = 100,
    use_default_theme = TRUE,
    show_origin = FALSE,
    retain_axis_scales = TRUE,
    modify_obj = FALSE) {

  # errors/warnings:
  if (is.null(seurat_obj@reductions[["umap"]])) {stop("No UMAP reduction found on the seurat object")}
  if (max_repulsion_iter > 1000) {
    warning("Repulsion iteration count is high, consider reducing max_repulsion_iter if runtime is too long")
  }

  # integrate TCR
  integrated_seurat_obj <- integrate_tcr(seurat_obj, tcr_df)
  if (modify_obj) {seurat_obj <- integrated_seurat_obj}

  # show % integrated
  percent_integrated <- 100 - percent_na(integrated_seurat_obj)
  message(paste("\nPercent of cells integrated:", as.character(round(percent_integrated)), "%"))

  # get the clone sizes and cluster centroids
  clone_size_list <- get_clone_sizes(integrated_seurat_obj, scale_factor = clone_scale_factor) # need to scale
  centroid_list <- get_cluster_centroids(integrated_seurat_obj)

  # pack the plot
  result_plot <- plot_API(sizes = clone_size_list,
                          centroids = centroid_list,
                          rad_decrease = rad_scale_factor,
                          ORDER = ORDER,
                          try_place = try_place,
                          progbar = progbar,
                          repulse = repulse,
                          thr = repulsion_threshold,
                          G = repulsion_strength,
                          max_repulsion_iter = max_repulsion_iter,
                          n = res,
                          origin = show_origin)

  # retain axis scales on the resulting plot. The function is broken and needs to be fixed
  if (retain_axis_scales) {
    result_plot <- retain_scale(seurat_obj, result_plot)
  }

  #set theme
  if (use_default_theme) {
    result_plot <- result_plot +
      ggplot2::theme_classic() +
      ggplot2::xlab("UMAP_1") +
      ggplot2::ylab("UMAP_2") +
      ggplot2::ggtitle("Sizes of clones within each cluster")
  }

  if (!modify_obj) {rm("integrated_seurat_obj")} # not sure if nessecary

  return(result_plot)
}
