# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_APackOfTheClones_wrappers", use_symbols = TRUE, package_name = "APackOfTheClones")

#' @docType package
#' @usage NULL
#' @useDynLib APackOfTheClones, .registration = TRUE
NULL

distV <- function(c1, c2) .Call(wrap__distV, c1, c2)


# nolint end
