# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_APackOfTheClones_wrappers", use_symbols = TRUE, package_name = "APackOfTheClones")

#' @docType package
#' @usage NULL
#' @useDynLib APackOfTheClones, .registration = TRUE
NULL

rust_sum <- function(component_vector) .Call(wrap__rust_sum, component_vector)


# nolint end
