# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
get_clone_sizes_Cpp <- function(barcodes, clusters, clonotype_ids, num_clusters, scale_factor) {
    .Call(`_scballpack_get_clone_sizes_Cpp`, barcodes, clusters, clonotype_ids, num_clusters, scale_factor)
}

