# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_average_vector <- function(vec_list) {
    .Call(`_APackOfTheClones_get_average_vector`, vec_list)
}

get_component_repulsion_vector <- function(inp, i, j, G) {
    .Call(`_APackOfTheClones_get_component_repulsion_vector`, inp, i, j, G)
}

