#' @title
#' Run the APackOfTheClones method on a combined Seurat object for
#' downstream visualization of clonal expansion
#'
#' @description
#' Computes all necessary information for an APackOfTheClones
#' clonal expansion plot and stores it in the seurat object at
#' `seurat_obj@reduction[['apotc']]` for use later with `APOTCPlot`. Gets sizes
#' of unique clones and utilizes a circle-packing algorithm to pack circles
#' representing individual clones in approximately the same dimensional
#' reduction (`reduction_base`) coordinates.
#'
#' @details If the user wishes to manually customize/fix the expansion plot
#' generated by `APOTCPlot`, the circular packing information can be modified
#' with the `AdjustAPOTC` function, or alternatively accessed via the syntax
#' `seurat_obj@reduction[['apotc']]` which harbours the custom S4 object of the
#' class `apotc`. Please read the function level documentation for the mentioned
#' functions and class, and also the web-only user vignette for a walkthrough of
#' the inner workings of the package.
#'
#' @param seurat_obj Seurat object with one or more dimension reductions. Must
#' already have been integrated with a T cell library via
#' `integrate_tcr(seurat_obj, tcr_df)`
#' @param reduction_base character. The seurat reduction to base the clonal
#' expansion plotting on. Defaults to `'umap'` but can also be `'tsne'` or
#' `'pca'`. If `'pca'``, the cluster coordinates will be based on PC1 and PC2.
#' However, generally APackOfTheClones is used for displaying UMAP and
#' occasionally t-SNE versions to intuitively highlight clonal expansion
#' @param clone_scale_factor Dictates how much to scale each circle(between 0,1)
#' radius when converting from clonotype counts into circles that represent
#' individual clonotypes. The argument defaults to the character `"auto"`, and
#' if so, the most visually pleasing factor will be estimated
#' @param rad_scale_factor numeric between 0 and 1. This value decreases the
#' radius of the smallest clones by this scale factor. And the absolute value
#' of this decrease will be applied to all packed circles, effectively shrinking
#' all circles on the spot, and introduce more constant spacing in between
#' @param ORDER logical. Decides if the largest clone circles should be at
#' cluster centroids
#' @param scramble logical. Decides if the clone circles within each cluster
#' should be randomly scrambled when plotted
#' @param try_place If `TRUE`, always minimizes distance from a newly placed
#' circle to the origin in the circle packing algorithm
#' @param repulse If `TRUE`, will attempt to push overlapping clusters away from
#' each other
#' @param repulsion_threshold numeric. The radius that clonal circle clusters
#' overlap is acceptable when repulsing
#' @param repulsion_strength numeric. The smaller the value the less the
#' clusters repulse each other per iteration, and vice versa
#' @param max_repulsion_iter integer. The number of repulsion iterations
#' @param verbose logical. Decides if visual cues print to the R console of the
#' progress
#'
#' @return A modified version of the input seurat object with a new object in
#' the `@reduction` attribute named `apotc`, which harbors data necessary for
#' visualizing the clonal expansion of the cells with the [APOTCPlot] function
#'
#' @seealso [APOTCPlot], [AdjustAPOTC]
#'
#' @export
#'
#' @examples
#' # unfinished
#'
RunAPOTC <- function(
    seurat_obj,
    reduction_base = "umap",
    # samples?
    # cloneCall?

    clone_scale_factor = "auto",
    rad_scale_factor = 0.95,
    ORDER = TRUE,
    scramble = FALSE,
    try_place = FALSE,

    repulse = FALSE,
    repulsion_threshold = 1,
    repulsion_strength = 1,
    max_repulsion_iter = 20L,
    verbose = TRUE
) {
    call_time <- Sys.time()

    reduction_base <- attempt_correction(reduction_base) # there can be a nice err msg scannign thru avaliable reductions

    # errors/warnings:
    warn_str <- run_apotc_warn_str(
        seurat_obj, reduction_base, clone_scale_factor, ORDER, scramble
    )
    if (!is.null(warn_str)) { stop(warn_str) }
    if (rad_scale_factor < 0 || rad_scale_factor > 1) {
        stop("rad_scale_factor has to be between 0 and 1")
    }

    # actual run
    if (verbose) {message("Initializing APOTC run")}


    if (should_estimate(clone_scale_factor)) {
        clone_scale_factor <- estimate_clone_scale_factor(seurat_obj, verbose)
    }

    rad_decrease <- convert_to_rad_decrease(rad_scale_factor,clone_scale_factor)

    #seurat_obj@commands[["RunAPOTC"]] <- make_apotc_command(call_time) # unsure how to handle the series of commands tbh since this should be ran multiple times.

    # initialize apotc S4 class
    apotc_obj <- initialize_apotc(
        get_num_clusters(seurat_obj),
        clone_scale_factor,
        rad_scale_factor, # maybe should be rad_decrease in the future?
        reduction_base
    )

    # infer clone sizes and centroids
    apotc_obj <- add_raw_clone_sizes(apotc_obj, seurat_obj)
    initial_centroids <- get_cluster_centroids(seurat_obj, reduction_base)

    packed_clusters <- pack_into_clusterlists(
        sizes = get_processed_clone_sizes(apotc_obj),
        centroids = initial_centroids,
        num_clusters = apotc_obj@num_clusters,
        rad_decrease = rad_decrease,
        ORDER = ORDER,
        scramble = scramble,
        try_place = try_place,
        verbose = verbose
    )

    if (repulse) {
        results <- get_repulsed_clusterlists_and_centroids(
            packed_clusters, initial_centroids, apotc_obj@num_clusters,
            repulsion_threshold, repulsion_strength, max_repulsion_iter, verbose
        )
        packed_clusters <- results[[1]]
        initial_centroids <- results[[2]]
    }

    # add the clusterlists and centroids to the obj
    apotc_obj@clusters <- packed_clusters
    apotc_obj@centroids <- initial_centroids
    apotc_obj@label_coords <- initial_centroids

    # add the finished apotc object to reductions, print message, and return
    seurat_obj@reductions[['apotc']] <- apotc_obj

    if (verbose) {
        print_completion_time(call_time)
    }

    seurat_obj
}

# for the ApotcData to get the right subset for clonotype data
convert_to_filter_condition <- function() {
  # TODO
}